### ISSUE TITLE
WinError 5 Access is denied

### ISSUE THREAD

**Issue by jonoyay** [BlueAmulet/GreenLuma-2020-Manager#11]
ERROR:root:Traceback (most recent call last):
  File "Qt\logic.py", line 243, in run_GLR
  File "subprocess.py", line 951, in __init__
  File "subprocess.py", line 1420, in _execute_child
PermissionError: [WinError 5] Access is denied
NoneType: None

**Comment by BlueAmulet** [comment]
This issue will be looked into, for now try to make sure that DLLInjector.exe and Steam.exe don't have "Run as administrator" checked in properties
