### ISSUE TITLE
Network error?

### ISSUE THREAD

**Issue by KrisCris** [BlueAmulet/GreenLuma-2020-Manager#12]
```
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): store.steampowered.com:443
ERROR:root:HTTPSConnectionPool(host='store.steampowered.com', port=443): Max retries exceeded with url: /search/results?term=MONSTER+HUNTER+RISE&count=25&start=0&category1=998 (Caused by ProxyError('Cannot connect to proxy.', OSError(0, 'Error')))
Traceback (most recent call last):
  File "site-packages\urllib3\connectionpool.py", line 696, in urlopen
  File "site-packages\urllib3\connectionpool.py", line 964, in _prepare_proxy
  File "site-packages\urllib3\connection.py", line 359, in connect
  File "site-packages\urllib3\connection.py", line 496, in _connect_tls_proxy
  File "site-packages\urllib3\util\ssl_.py", line 432, in ssl_wrap_socket
  File "site-packages\urllib3\util\ssl_.py", line 474, in _ssl_wrap_socket_impl
  File "ssl.py", line 500, in wrap_socket
  File "ssl.py", line 1040, in _create
  File "ssl.py", line 1309, in do_handshake
OSError: [Errno 0] Error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages\requests\adapters.py", line 439, in send
  File "site-packages\urllib3\connectionpool.py", line 755, in urlopen
  File "site-packages\urllib3\util\retry.py", line 573, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='store.steampowered.com', port=443): Max retries exceeded with url: /search/results?term=MONSTER+HUNTER+RISE&count=25&start=0&category1=998 (Caused by ProxyError('Cannot connect to proxy.', OSError(0, 'Error')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "core.py", line 269, in queryGames
  File "site-packages\requests\api.py", line 76, in get
  File "site-packages\requests\api.py", line 61, in request
  File "site-packages\requests\sessions.py", line 542, in request
  File "site-packages\requests\sessions.py", line 655, in send
  File "site-packages\requests\adapters.py", line 510, in send
requests.exceptions.ProxyError: HTTPSConnectionPool(host='store.steampowered.com', port=443): Max retries exceeded with url: /search/results?term=MONSTER+HUNTER+RISE&count=25&start=0&category1=998 (Caused by ProxyError('Cannot connect to proxy.', OSError(0, 'Error')))
```

**Comment by saglb** [comment]
hi guy,i have the same problem. solve this problem?

**Comment by KrisCris** [comment]
no, i gave up. just manually copy and paste all the appid

**Comment by BlueAmulet** [comment]
This error states it cannot connect to your internet proxy, is it possible you have bad proxy settings?
