### ISSUE TITLE
Search function error

### ISSUE THREAD

**Issue by mirrorb** [BlueAmulet/GreenLuma-2020-Manager#19]
![image](https://user-images.githubusercontent.com/34116207/157373911-f411b124-29ba-4255-aff4-a641376c02c9.png)

**Comment by mirrorb** [comment]
> INFO:root:GreenLuma 2020 Manager 1.3.8.7
> DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): store.steampowered.com:443
> ERROR:root:('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
> Traceback (most recent call last):
>   File "urllib3\connectionpool.py", line 710, in urlopen
>   File "urllib3\connectionpool.py", line 449, in _make_request
>   File "<string>", line 3, in raise_from
>   File "urllib3\connectionpool.py", line 444, in _make_request
>   File "http\client.py", line 1369, in getresponse
>   File "http\client.py", line 310, in begin
>   File "http\client.py", line 279, in _read_status
> http.client.RemoteDisconnected: Remote end closed connection without response
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "requests\adapters.py", line 450, in send
>   File "urllib3\connectionpool.py", line 786, in urlopen
>   File "urllib3\util\retry.py", line 550, in increment
>   File "urllib3\packages\six.py", line 769, in reraise
>   File "urllib3\connectionpool.py", line 710, in urlopen
>   File "urllib3\connectionpool.py", line 449, in _make_request
>   File "<string>", line 3, in raise_from
>   File "urllib3\connectionpool.py", line 444, in _make_request
>   File "http\client.py", line 1369, in getresponse
>   File "http\client.py", line 310, in begin
>   File "http\client.py", line 279, in _read_status
> urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "core.py", line 271, in queryGames
>   File "requests\api.py", line 75, in get
>   File "requests\api.py", line 61, in request
>   File "requests\sessions.py", line 529, in request
>   File "requests\sessions.py", line 645, in send
>   File "requests\adapters.py", line 501, in send
> requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
