### ISSUE TITLE
The tool does not work properly, and when I run it, the program has the following error.

### ISSUE THREAD

**Issue by zyh7012109808** [BlueAmulet/GreenLuma-2020-Manager#21]
Traceback (most recent call last):
  File "main.py", line 5, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "Qt\logic.py", line 13, in <module>
  File "core.py", line 85, in __init__
  File "core.py", line 97, in load_profiles
  File "json\__init__.py", line 293, in load
UnicodeDecodeError: 'gbk' codec can't decode byte 0xa2 in position 50: illegal multibyte sequence

**Comment by BlueAmulet** [comment]
Hmm, that's a particularly nasty issue to try and fix. I'd want to fix this by ensuring all profiles are written and loaded as UTF-8 rather than the system codec, but making that change risks breaking existing profiles for certain regions of the world, or having them being misinterpreted.

For your issue in particular, did this happen after using it for the first time, or did it break after a while?

**Comment by zyh7012109808** [comment]
The problem was identified. When I opened the folder, I saw a ".docx "file that I had created. I think that's what caused the crash. : D

It seems that if you want your program to run correctly forever, you can't leave any other files in this folder. When the program runs, it will automatically call all files under the "profile" folder and run.

**Comment by BlueAmulet** [comment]
Should also be fixed by 776cf4d77d46b33f975f978d416a0f87b5ba694b when a release is made.
